version: "3.8"
services:
  postgres:
    container_name: mobile-db
    image: ankane/pgvector
    ports:
      - "5432:${DB_PORT}"
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: raidrockstar040@gmail.com
      PGADMIN_DEFAULT_PASSWORD: lol
    depends_on:
      - postgres
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  pgdata:
  pgadmin-data:
  redis-data:
